#+TITLE:  MSc-Thesis Projects 2023
#+AUTHOR: Dirk Oliver Theis, University of Tartu, Estonia
#+EMAIL:  dotheis@ut.ee
#+DATE:   Tue Sep 26 18:39:41 EEST 2023

#+STARTUP: latexpreview
#+STARTUP: show3levels
#+BIBLIOGRAPHY: ../../DOT_LaTeX/dirks.bib
#+PROPERTY: header-args :eval never :comments link :exports code
#+SEQ_TODO: TODO REVIEW | DONE

* OpenSuperQ

   UTartu is part of an EU effort to build hardware, enabling software (firmware, OS, compiler), and application
   software for a first large-scale made-in-EU quantum computer: [[https://opensuperqplus.eu/][OpenSuperQ]].

-----
** *»Compiler«* -- Quantum-Compiler Construction

     The student's contribution will be to develop in Python, based on existing open-source code by IBM, Google,
     etc, a compiler for quantum programs, that integrates with the planned OpenSuperQ operating system and
     middleware.

     + Computer Science ::
       - Area:                   /Quantum circuits manipulation/
       - Required background:    /Content of FunQ ([[https://ois2.ut.ee/#/courses/LTFY.04.012/version/d9ad2597-0612-5609-960c-c2340984c793/details][LTFY.04.012 Fundamentals of Quantum Computing]])/
       - Recommended background: /Compiler construction (e.g., [[https://courses.cs.ut.ee/2023/AKT][LTAT.03.006, Automaadid, keeled ja translaatorid]])/

     + Programming ::
       - Python (incl. [[https://qiskit.org/][Qiskit]])

     _Supervision & Inquiries_

     #+BEGIN_EXAMPLE
     Dirk Oliver Theis
     Assoc. Prof. Theoretical Computer Science
     dotheis.UTartu@gmail.com
     #+END_EXAMPLE

-----

** *»Verify«* -- Verification of the software stack

     The student's contribution will be to implement and assess the quality of methods for the verification of the
     correct functioning of the stack of the OpenSuperQ+ quantum computers.

     + Computer Science ::
       - Area:                   /Quantum information processing/
       - Required background:    /Content of FunQ ([[https://ois2.ut.ee/#/courses/LTFY.04.012/version/d9ad2597-0612-5609-960c-c2340984c793/details][LTFY.04.012 Fundamentals of Quantum Computing]])/
       - Recommended background: /Basic stabilizer theory (e.g., read § 10.5 in [[https://en.wikipedia.org/wiki/Quantum_Computation_and_Quantum_Information][Nielsen-Chuang]])/

     + Programming ::
       - Python (incl. [[https://qiskit.org/][Qiskit]])

     _Supervision & Inquiries_

     #+BEGIN_EXAMPLE
     Dirk Oliver Theis
     Assoc. Prof. Theoretical Computer Science
     dotheis.UTartu@gmail.com
     #+END_EXAMPLE

-----


* NeQst

   UTartu is part of a project called [[https://www.sintef.no/en/projects/2022/neqst-quantum-computing-applied-to-industrial-optimization-problems/][NeQst]] that includes 5 industrial partners, with the aim to assess the
   feasibility of industrial optimization on pre-fault-tolerant quantum computers[fn:1].  The approach taken is
   closely linked to quantum neural networks.

   Specifically, one of UTartu's roles is to minimize the detrimental influence of statistical noise in the
   measurement results on the algorithm performance.

-----
** *»SiPSA«* -- Gradients in quantum neural networks

     One bottleneck for building artificial neural networks that process quantum information is the high cost of
     computing gradients: While in classical neural networks, gradient computation is as costly as function
     evaluation, in the (currently proposed) quantum settings, the cost is higher by a factor between $\sqrt d$
     and $d$ (where $d$ is the number of parameters to be "trained").

     The student's contribution will lie in writing code for and assessment of the »[[https://en.wikipedia.org/wiki/Simultaneous_perturbation_stochastic_approximation][Simultaneous Perturbation
     Stochastic Approximation]]« method for gradient estimates -- which, deceptively, seems to promise to reduce
     that factor to $O(1)$ -- and compare it to clever implementations of two other methods.  A number of
     technological hurdles have to be overcome.

     + Mathematics ::
       - Area:                   /Stochastic optimization of smooth functions/
       - Required background:    /Continuous optimization; Statistics/
       - Recommended background: /Fourier analysis/

     + Programming ::
       - Either:   [[https://julialang.org/][Julia]] ("Julia is the new MATLAB"), preferred;
       - Or:       Python.

       The student is free to choose the programming language.  The code will have to simulate parameterized
       quantum computations with tons of thousands of parameters, and be run tens of thousands of times -- which
       may not be feasible in Python.  Julia, on the other hand, is about as fast as un-optimized C code to begin
       with, and it also makes it easy to deploy multi-core SIMD (GPU) parallelization.

     _Supervision & Inquiries_

     #+BEGIN_EXAMPLE
     Dirk Oliver Theis
     Assoc. Prof. Theoretical Computer Science
     dotheis.UTartu@gmail.com
     #+END_EXAMPLE

-----


* Mathematics of Quantum Information Processing
-----
** *»Spectrum«* -- Fourier spectra of parametric unitaries

     The student's contribution will lie in generalizing a theorem about the Fourier spectra of certain smooth,
     bounded, non-$\mathcal C_0$ functions (➜ basic tempered distribution theory probably necessary) from finite
     dimension (function values are unitary matrices) to infinite dimension (function values are unitary operators
     on an infinite-dimensional Hilbert space).

     + Mathematics ::
       - Area:                   /Functional analysis/
       - Required background:    /Fourier analysis/
       - Recommended background: /Tempered distributions/

     + Programming ::
       %

     _Supervision & Inquiries_

     #+BEGIN_EXAMPLE
     Evgenii Dolzhkov                    Dirk Oliver Theis
     Cand. PhD                           Assoc. Prof. Theoretical Computer Science
     evgenii.dolzhkov@ut.ee              dotheis.UTartu@gmail.com
     #+END_EXAMPLE

-----

** *»Concentration«* -- Derivative-computing measures with strong concentration

     The student's contribution will lie in trying to generalize a theorem about the non-existence of (signed /
     complex) Borel measures $\mu$ with
     #+BEGIN_CENTER
                  \[
                  \int f\,d\mu = f'(0) \quad\forall f\in L^2(\mathbb R) \text{ with } \mathrm{Supp\,}\hat f \subseteq [-1/2,+1/2].
                  \]
     #+END_CENTER
     The existing theorem states that such a $\mu$ cannot have exponential concentration around 0, i.e., no such
     $\mu$ satisfies
     #+BEGIN_CENTER
                  \[
                  \int_{-R}^{+R} d\mu = e^{-\Omega(R)}.
                  \]
     #+END_CENTER
     Any improvement of this condition will count as a generalization.

     + Mathematics ::
       - Area:                   /Functional analysis/
       - Required background:    /Fourier analysis/
       - Recommended background: /Proof of the Paley-Wiener theorem/

     _Supervision & Inquiries_

     #+BEGIN_EXAMPLE
     Evgenii Dolzhkov                    Dirk Oliver Theis
     Cand. PhD                           Assoc. Prof. Theoretical Computer Science
     evgenii.dolzhkov@ut.ee              dotheis.UTartu@gmail.com
     #+END_EXAMPLE

-----

** *»Dirichlet«* -- Signs of modified Dirichlet kernels
      The student's contribution will *hopefully(!!)* lie in proving a conjecture about signs of modified Dirichlet
      kernels.

      + Mathematics ::
        - Area:                   /Classical analysis/
        - Recommended background: /Fourier analysis/
        - Required:               /Superior problem solving skills/

      + Programming ::
        %

     _Supervision & Inquiries_

     #+BEGIN_EXAMPLE
     Evgenii Dolzhkov                    Dirk Oliver Theis
     Cand. PhD                           Assoc. Prof. Theoretical Computer Science
     evgenii.dolzhkov@ut.ee              dotheis.UTartu@gmail.com
     #+END_EXAMPLE

-----


* Miscellaneous
-----
** *»Clouds«* -- Data structures for point clouds with density-queries

     #+BEGIN_CENTER
     *CONFIDENTIAL!*
     #+END_CENTER

     The use-case in quantum information of the following thesis projects is confidential intellectual property,
     and all information related to the use-case and the connection to these projects are sensitive.

     _Supervision & Inquiries_

     #+BEGIN_EXAMPLE
     Dirk Oliver Theis
     Assoc. Prof. Theoretical Computer Science
     dotheis.UTartu@gmail.com
     #+END_EXAMPLE

**** »Clouds-DS«

     The student's contribution will consist in researching (classical-computer) data structures that allow to
     store large sets of high-dimensional points, with the requirement that, after storage and potentially
     post-processing, regions of high density (many points per volume) can be retrieved from the data structure.
     The supervisor is, at the time of writing this, not aware whether such data structures exist.

     The use-case in quantum information of this type of data structures are confidential in the sense of
     intellectual property protection.

     + Computer Science ::
       - Area:                   /Advanced data structures & algorithms/
       - Recommended background: /Theory of algorithms and data structures/

       The project will include a theoretical analysis of space & time requirements.

     + Programming ::
       - Either:   [[https://julialang.org/][Julia]] ("Julia is the new MATLAB"), preferred;
       - Or:       Python.

       The project will include an implementation of a simulation that mimicks the actual quantum-information
       use-case -- a Python implementation /might/ be too slow for that.

**** »Clouds-NN«

     Same as above, except where identifying high density regions is based on Neural Networks -- and hence without
     the theory component, of course.

     + Computer Science ::
       - Area:                   /Machine learning/

     + Programming ::
       - Python

-----


* Footnotes
[fn:1] Spoiler alert: Works like shit.
# Local Variables:
# fill-column: 115
# End:
